name: "hubspot-integration"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
